# Generated by Django 5.2.3 on 2025-07-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbc_handler', '0003_rename_parsed_data_dbcdata_data_dbcmessage_dbcsignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcsignal',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='dbc_handler.dbcmessage'),
        ),
    ]
