# Generated by Django 5.2.3 on 2025-07-07 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbc_handler', '0004_alter_dbcsignal_message'),
        ('mapper', '0001_initial'),
        ('projects', '0002_alter_project_owner'),
        ('vss_handler', '0004_alter_vsssignal_api_name_alter_vsssignal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vssdbcmappingdata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vss_dbc_mappings', to='projects.project'),
        ),
        migrations.CreateModel(
            name='VssDbcMappingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('dbc_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='dbc_handler.dbcsignal')),
                ('mapping_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mapper.vssdbcmappingdata')),
                ('vss_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='vss_handler.vsssignal')),
            ],
        ),
    ]
