# Generated by Django 5.2.3 on 2025-07-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_alter_vssdbcmappingdata_project_vssdbcmappingentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vssdbcmappingdata',
            name='mapping_data',
        ),
    ]
