# Generated by Django 5.2.3 on 2025-07-08 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_remove_vssdbcmappingdata_mapping_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VssDbcMappingTransform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('dbc2vss', 'DBC to VSS'), ('vss2dbc', 'VSS to DBC')], max_length=16)),
                ('interval_ms', models.IntegerField(blank=True, null=True)),
                ('math', models.CharField(blank=True, max_length=255, null=True)),
                ('mapping', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transforms', to='mapper.vssdbcmappingentry')),
            ],
        ),
    ]
