# Generated by Django 5.2.3 on 2025-07-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_vssdbcmappingtransform'),
        ('vss_handler', '0004_alter_vsssignal_api_name_alter_vsssignal_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vssdbcmappingentry',
            unique_together={('mapping_data', 'vss_signal')},
        ),
    ]
