# Generated by Django 5.2.3 on 2025-07-07 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vss_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vssdata',
            name='signals',
        ),
        migrations.CreateModel(
            name='VSSSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('datatype', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('vss_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VSSsignals', to='vss_handler.vssdata')),
            ],
        ),
    ]
