# Generated by Django 5.2.3 on 2025-07-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vss_handler', '0002_remove_vssdata_signals_vsssignal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsssignal',
            name='path',
        ),
        migrations.AddField(
            model_name='vsssignal',
            name='api_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vsssignal',
            name='api_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='vsssignal',
            name='api_uuid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vsssignal',
            name='parent_api_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='vsssignal',
            name='type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='vsssignal',
            name='vss_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vss_signals', to='vss_handler.vssdata'),
        ),
    ]
