# Generated by Django 5.2.3 on 2025-07-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vss_handler', '0003_remove_vsssignal_path_vsssignal_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsssignal',
            name='api_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='vsssignal',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
